### ISSUE TITLE
Link alias to MAC address

### ISSUE THREAD

**Issue by qualiaa** [mcnutty26/music-get#13]
Consider linking aliases to MAC addresses in case IPs get reallocated during a LAN

If I get assigned "McNutty" by accident, you know what I'm going to queue.

**Comment by mcnutty26** [comment]
Unfortunately MAC addresses aren't included in the HTTP request received by the server (damned abstraction!). We could do some crazy ARP lookup or similar to get access to the lower levels of the network stack, but it looks like this would be significantly more effort than increasing the DHCP lease time to 5 days.

**Comment by qualiaa** [comment]
Just a note that due to this issue I was able to queue two times my normal regimen of music for the Sunday morning. I hope you're pleased with yourself.

**Comment by mcnutty26** [comment]
One of the reasons that this was dropped was that it doesn't actually solve the problem. If this was implemented then you would just spoof a different MAC address. Suppose we had implemented accounts, then you would have just made a new account :P 

Whatever we do to try and prevent this, people will find a way!

**Comment by qualiaa** [comment]
No, we don't aim to prevent people intentionally defeating the system. The
problem is that I was reassigned a different IP address on rebooting. Chris
was reassigned without rebooting. We had no choice but to double queue.
