### ISSUE TITLE
Queues failed items

### ISSUE THREAD

**Issue by Veltas** [mcnutty26/music-get#21]
When youtube-dl fails to download a file nothing is saved (trying to access the item 404s) but a queue entry is still made and there is no feedback to suggest something went wrong.

**Comment by mcnutty26** [comment]
As of (at least) the current build, queueing a URL which doesn't have a file will no longer enters an empty item into the queue. In YoutubeDownloader.java the name of the video file gets checked, and if it's empty then the item does not get passed to ProcessQueue.java (https://github.com/mcnutty26/music-get/blob/master/src/main/java/mcnutty/music/get/YoutubeDownload.java#L54).

Files remain a trickier problem in this regard, as there isn't really a way to dry run mplayer to see if it can play something. I think it's safe to just trust that people won't get mad when we don't play their JPEGs.
