### ISSUE TITLE
Queue page alias box wraps too early

### ISSUE THREAD

**Issue by Veltas** [mcnutty26/music-get#22]
The HTML page for the queue text-wraps the aliases of people who queued items in the long list even if there is plenty of space for the alias to fit on one line.

**Comment by mcnutty26** [comment]
This should be easy, as aliases are truncated to 20 characters anyway in playing.php

**Comment by Veltas** [comment]
Yeah not really sure why stuff is wrapping so early as it is

**Comment by mcnutty26** [comment]
Should be fixed in d0e298ca2603c0f4436420444e88652388177947
