### ISSUE TITLE
Reload config feature

### ISSUE THREAD

**Issue by Veltas** [mcnutty26/music-get#29]
Depends on https://github.com/mcnutty26/music-get/issues/28

An admin-only 'reload' feature would be appropriate, to let us change config without restarting the server

**Comment by mcnutty26** [comment]
As it currently stands, the password is loaded dynamically, so the only things we'd need to change are bucket limit, storage directory, and timeout. Not sure that those are things we need to change often enough to make it worth it?

**Comment by mcnutty26** [comment]
Passwords loaded dynamically as of e8baace2f074e4d1776d0691284a556187c0871d
Bucket limit loaded dynamically as of 996e6c15bd4539280b60d2f034987a5870fbea38
Storage directory is still startup only, but I think this is OK as dynamically changing it is more difficult
Timeout loaded dynamically as of abbbc1be4ea4b0c25c57507555d2412d1f20cd6c
