### ISSUE TITLE
AJAX the queue?

### ISSUE THREAD

**Issue by Phillammon** [mcnutty26/music-get#3]
Currently necessary to reload to see changes. It's [CURRENT YEAR], that shouldn't be necessary/

Steps to reproduce:
1) Be at LAN.
2) Don't refresh the page for two days
3) Be confused by the queue

**Comment by Veltas** [comment]
Registering my interest with this feature

**Comment by mcnutty26** [comment]
Feature added as of 1e09e221afff61622ad212f47c1e81318e0ce420
