### ISSUE TITLE
IP addresses get mangled by the proxy

### ISSUE THREAD

**Issue by mcnutty26** [mcnutty26/music-get#37]
Everyone appears as the servers IP, caused by Apache proxying requests to the backend

**Comment by Veltas** [comment]
apache the absolute madman

**Comment by mcnutty26** [comment]
Fixed in 853a34d5c05375ec046423d335be7a270ac8c10d by having ProcessServer check X-Forwarded-For instead of relying on the source IP of the request (which was always the IP of the server Apache was running on)
