### ISSUE TITLE
Stream currently playing music

### ISSUE THREAD

**Issue by zed0** [mcnutty26/music-get#7]
It would be nice to be able to listen to the music server via headphones or while not at LAN (though there are potentially (even more) copyright issues here).
An icecast stream or some other sort of live stream would be neat.

**Comment by mcnutty26** [comment]
Closing as this is solved by running software on the machine itself, as opposed to music-get (which is not available externally). Listening to the currently playing track via headphones is less of a pressing issue when it's being blasted out of the speakers in the room :smile:
